services:
  - type: web
    name: medikiosk
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: BEY_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://venerable-selkie-bda1c2.netlify.app,https://mediliosk.onrender.com
